platform :ios, "5.1"

#link_with ['PrYv-iOS-Example', 'PrYv-iOS-ExampleTests']

pod 'PryvApiKit', :path => '../../PryvApiKit.podspec'

# target 'PrYv-iOS-Example' do
#     pod 'PryvApiKit', :path => '../../PryvApiKit.podspec'
# end

target 'PrYv-iOS-ExampleTests', :exclusive => true do
  #pod 'PryvApiKit', :path => '../../PryvApiKit.podspec'
  pod 'OCMock'
  pod 'Mocktail'
end